export const id = {
    common: {
        dashboard: 'Dashboard',
        search: 'Cari',
        save: 'Simpan',
        saving: 'Menyimpan...',
        cancel: 'Batal',
        delete: 'Hapus',
        edit: 'Edit',
        add: 'Tambah',
        close: 'Tutup',
        viewAll: 'Lihat semua',
        actions: 'Aksi',
        all: 'Semua',
        loading: 'Memuat...',
        noData: 'Belum ada data.',
        back: 'Kembali',
        confirm: 'Konfirmasi',
        yes: 'Ya',
        no: 'Tidak',
        showing: 'Menampilkan',
        of: 'dari',
        perPage: 'per halaman',
        entries: 'data',
        previous: 'Sebelumnya',
        next: 'Selanjutnya',
        total: 'Total',
        active: 'Aktif',
        inactive: 'Tidak Aktif',
        optional: 'opsional',
        searchPlaceholder: 'Cari...',
    },
    layout: {
        brand: 'Sistem Kepatuhan Digital',
        suite: 'Compliance Suite',
        mainMenu: 'Menu Utama',
        administration: 'Administrasi',
        notifications: 'Notifikasi',
        markRead: 'Tandai dibaca',
        profile: 'Profil Saya',
        changePassword: 'Ubah Kata Sandi',
        logout: 'Keluar',
        new: 'baru',
        toggleSidebar: 'Buka/tutup menu',
        closeSidebar: 'Tutup menu',
        toggleTheme: 'Ganti tema terang/gelap',
    },
    role: {
        superadmin: 'Super Admin',
        admin_kepatuhan: 'Admin Kepatuhan',
        koordinator_smki: 'Koordinator SMKI',
        auditor: 'Auditor',
        pic: 'PIC',
        system: 'Sistem SMKI',
    },
    dashboard: {
        title: 'Dashboard',
        subtitle: 'Ringkasan kepatuhan organisasi',
        welcomeBack: 'Selamat datang kembali',
        overallCompliance: 'Kepatuhan Keseluruhan',
        activeStandards: 'Standar Aktif',
        pendingActions: 'Tindakan Tertunda',
        nonCompliances: 'Tidak Patuh',
        compliance: 'Kepatuhan',
        controls: 'kontrol',
        target: 'Target',
        trend: 'Tren Kepatuhan',
        riskAssessment: 'Asesmen Risiko',
        riskRegister: 'Buka register',
        recentAudit: 'Audit Terbaru',
        time: 'Waktu',
        user: 'Pengguna',
        action: 'Aksi',
        module: 'Modul',
        status: 'Status',
        pending: 'Menunggu',
        approved: 'Disetujui',
        rejected: 'Ditolak',
        automatic: 'Otomatis',
        todo: 'Tindakan yang Harus Dilakukan',
        actionsPending: 'aksi',
        evidencePending: 'Evidence pending',
        overdue: 'Overdue',
        critical: 'Critical',
        active: 'Aktif',
        verification: 'Verifikasi',
        open: 'Buka',
        period: 'Periode',
        thisMonth: 'bln ini',
        needsAction: 'Perlu Tindakan',
        mitigationInProgress: 'Mitigasi dalam proses',
        frameworkOverview: 'Ringkasan Framework Utama',
        frameworkProgress: 'Progres implementasi kontrol kepatuhan standar ISO',
        compliant: 'Patuh',
        partial: 'Sebagian',
        nonCompliant: 'Tidak Patuh',
        na: 'Tidak Berlaku',
        recentActivity: 'Aktivitas & Catatan Terbaru',
        session: 'Session',
        progress: 'Progress',
        framework: 'Framework',
    },
    compliance: {
        title: 'Frameworks & Controls',
        subtitle: 'Pilih framework untuk menelusuri kontrol & klausul dalam satu layar.',
        addControl: 'Tambah Kontrol',
        addFramework: 'Tambah Framework',
        addFrameworkHint: 'Grid menyesuaikan jumlah framework',
        allFrameworks: 'Semua Framework',
        allStatus: 'Semua Status',
        allUnits: 'Semua Unit',
        filter: 'Filter',
        searchPlaceholder: 'Cari kode atau judul kontrol…',
        code: 'Kode',
        controlClause: 'Kontrol / Klausul',
        category: 'Kategori',
        workUnit: 'Unit Kerja',
        status: 'Status',
        actions: 'Aksi',
        controlsUnit: 'kontrol',
        compliantPct: 'compliant',
        controlsManagement: 'Manajemen Keamanan Informasi',
        privacyManagement: 'Manajemen Informasi Privasi',
        noResults: 'Tidak ada kontrol yang cocok dengan kriteria pencarian.',
        noEntryYet: 'Belum ada penilaian untuk kontrol ini.',
        createTitle: 'Tambah Kontrol Baru',
        createSubtitle: 'Tambahkan kontrol ke dalam pustaka framework.',
        editTitle: 'Edit Kontrol',
        controlTitle: 'Judul Kontrol',
        codePlaceholder: 'Contoh: A.5.2',
        titlePlaceholder: 'Judul kontrol / klausul',
        description: 'Deskripsi',
        descriptionPlaceholder: 'Deskripsi lengkap kontrol…',
        frameworkLabel: 'Framework',
        categoryLabel: 'Kategori',
        addControlBtn: 'Simpan Kontrol',
        close: 'Tutup',
        openChecklistEntry: 'Buka Checklist Entry',
        detailRef: 'Referensi kontrol',
        detailDescriptionLabel: 'Deskripsi kontrol',
        unitsAssessed: 'Unit yang Dinilai Terhadap Kontrol Ini',
        unitWork: 'Unit Kerja',
        pic: 'PIC',
        cycleStatus: 'Status Siklus Berjalan',
        editControl: 'Edit Kontrol',
        deleteControl: 'Hapus Kontrol',
        deleteConfirm: (code: string, title: string) => `Hapus kontrol "${code} — ${title}"? Tindakan ini tidak dapat dibatalkan.`,
    },
    frameworks: {
        title: 'Manajemen Framework',
        subtitle: 'Kelola seluruh framework standar kepatuhan beserta dokumen referensinya.',
        addFramework: 'Tambah Framework',
        name: 'NAMA',
        version: 'VERSI',
        urlFile: 'DOKUMEN',
        controlsCount: 'JUMLAH KONTROL',
        editFramework: 'Edit Framework',
        deleteFramework: 'Hapus Framework',
        noResults: 'Tidak ada framework yang cocok dengan kriteria pencarian.',
        createTitle: 'Tambah Framework Baru',
        editTitle: 'Edit Framework',
        nameLabel: 'Nama Framework',
        namePlaceholder: 'Contoh: ISO/IEC 27001',
        versionLabel: 'Versi',
        versionPlaceholder: 'Contoh: 2022',
        dokumenHint: 'Format PDF, DOCX, CSV, atau XLSX (maks. 20MB). Kosongkan untuk mempertahankan dokumen yang ada.',
        chooseFile: 'Pilih File',
        noFileSelected: 'Belum ada dokumen terpilih',
        viewDocument: 'Lihat Dokumen',
        searchPlaceholder: 'Cari berdasarkan nama atau versi...',
        deleteConfirm: (nama: string, versi: string) => `Hapus framework "${nama} ${versi}"? Semua kontrol terkait juga akan dihapus.`,
    },
    superadmin: {
        title: 'Dashboard Superadmin',
        subtitle: 'Kelola seluruh konfigurasi sistem kepatuhan digital.',
        totalUsers: 'Total Users',
        allRoles: 'Semua role aktif',
        totalFrameworks: 'Framework',
        standardsRegistered: 'Standar kepatuhan terdaftar',
        totalControls: 'Total Kontrol',
        activeControls: 'Klausul aktif seluruh framework',
        policy: 'Kebijakan',
        comingSoon: 'Segera hadir',
        frameworkOverview: 'Framework Overview',
        frameworkList: 'Daftar seluruh framework kepatuhan',
        manage: 'Kelola',
        quickActions: 'Quick Actions',
        quickActionsDesc: 'Akses cepat ke manajemen sistem',
        frameworkManagement: 'Manajemen Framework',
        frameworkCrud: 'CRUD framework & kontrol',
        userManagement: 'Manajemen User',
        systemSettings: 'System Settings',
        auditLogs: 'Audit Logs',
        totalActiveUsers: 'Total Active Users',
        orgCompliance: 'Kepatuhan Organisasi',
        orgKpi: 'KPI Organisasi',
        riskRegisterShort: 'Register Risiko',
        riskRegisterDesc: 'Asesmen risiko kepatuhan',
        auditTrailShort: 'Audit Trail',
        auditTrailDesc: 'Rekam jejak aktivitas sistem',
        pendingAccess: 'Permintaan Akses Menunggu',
        recentLogins: 'Login Terakhir',
        recentActivities: 'Aktivitas Terbaru',
        viewAll: 'Lihat semua',
    },
    auth: {
        login: {
            title: 'Masuk — SMKI',
            subtitle: 'Sistem Kepatuhan Digital',
            email: 'Email',
            password: 'Password',
            submit: 'Masuk',
            forgotPassword: 'Lupa password?',
            chooseRole: 'Pilih peran Anda untuk login',
            roles: {
                superadmin: 'Super Admin',
                admin_kepatuhan: 'Admin Kepatuhan',
                koordinator_smki: 'Koordinator SMKI',
                auditor: 'Auditor',
                pic: 'PIC',
            },
        },
        forgot: {
            title: 'Lupa Password',
            subtitle: 'Masukkan email untuk mendapatkan tautan reset.',
            email: 'Email',
            submit: 'Kirim Tautan Reset',
            backToLogin: 'Kembali ke login',
        },
        brandPanel: {
            eyebrow: 'Sistem Kepatuhan Digital',
            headlineBefore: 'Kelola kepatuhan organisasi Anda dalam',
            headlineHighlight: 'satu platform.',
            footerQuote: 'Sistem Kepatuhan Digital membantu Anda menjaga kepatuhan standar ISO tetap transparan, terdokumentasi, dan siap diaudit.',
            features: {
                auditable: '100% dapat diaudit',
                centralized: 'Framework terpusat',
                notifications: 'Notifikasi real-time',
            },
            copyright: '© 2026 Direktorat Kepatuhan · v2.4.0',
        },
        welcomeBack: 'Selamat datang kembali',
        welcomeBackSubtitle: 'Masuk untuk mengakses dashboard kepatuhan Anda.',
        rememberMe: 'Ingat saya',
        showPassword: 'Tampilkan kata sandi',
        hidePassword: 'Sembunyikan kata sandi',
        secureNote: 'Koneksi terenkripsi · Aktivitas tercatat untuk audit',
        resetSent: 'Permintaan terkirim (fitur reset masih dalam pengembangan).',
    },
    checklist: {
        title: 'Checklist',
        subtitle: 'Penilaian kepatuhan per kontrol',
        myChecklist: 'My Checklist',
        allChecklists: 'All Checklists',
        frameworksControls: 'Frameworks & Controls',
        siklus: 'Siklus',
        kontrolUnit: 'kontrol',
        pic: 'PIC',
        filledOf: (filled: number, total: number) => `${filled} dari ${total} diisi`,
        createFinding: 'Buat Temuan',
        submitChecklist: 'Submit Checklist',
        saveDraft: 'Simpan Draft',
        patuh: 'Patuh',
        patuhDesc: 'Kontrol terpenuhi',
        sebagianPatuh: 'Sebagian Patuh',
        sebagianPatuhDesc: 'Kontrol terpenuhi sebagian',
        tidakPatuh: 'Tidak Patuh',
        tidakPatuhDesc: 'Ada gap terhadap kontrol',
        tidakBerlaku: 'Tidak Berlaku',
        tidakBerlakuDesc: 'Di luar lingkup unit',
        catatanPlaceholder: 'Catatan (opsional)…',
        uploadEvidence: 'Unggah Bukti',
        evidenceCount: (n: number) => (n === 1 ? 'Evidence: 1 file' : `Evidence: ${n} file`),
        deadlineToday: 'Deadline hari ini 17:00',
        deadlineTomorrow: 'Deadline besok 17:00',
        belumDiisi: 'Belum diisi',
        draft: 'Draft',
        alertRejectedTitle: 'Submission ditolak oleh Compliance Admin',
        alertRejectedBody:
            'Evidence tidak terbaca / berkualitas rendah. Silakan upload ulang dokumen yang disetujui manajemen, lalu submit kembali sebelum deadline.',
        submitConfirmTitle: 'Submit checklist untuk verifikasi?',
        submitConfirmDesc: 'Setelah disubmit, entry tidak dapat diubah sampai admin memberikan keputusan.',
        submitConfirmStatus: 'Status',
        submitConfirmEvidence: 'Evidence',
        submitConfirmCatatan: 'Catatan',
        submitYes: 'Ya, Submit',
        draftConfirmTitle: 'Simpan sebagai draft?',
        draftConfirmDesc: 'Draft tersimpan dapat Anda lanjutkan kapan saja sebelum deadline.',
        draftYes: 'Simpan Draft',
        draftSaved: 'Draft checklist berhasil disimpan.',
        submitted: 'Checklist berhasil disubmit untuk verifikasi.',
        findingConfirmTitle: 'Buat temuan dari kontrol ini?',
        findingConfirmDesc: (code: string) => `Anda akan membuat temuan (non-conformity) yang tertaut ke kontrol ${code}.`,
        findingContinue: 'Lanjutkan ke Form Temuan',
        rejectedAlert: 'Komentar akan dikirim ke PIC dan masuk ke audit trail.',
        saveNote: 'Penilaian kontrol berhasil disimpan.',
    },
    findings: {
        title: 'Temuan',
        subtitle: 'Temuan ketidaksesuaian lintas unit · SLA 14 hari',
        kanban: 'Kanban',
        list: 'List',
        searchPlaceholder: 'Cari temuan…',
        allSeverity: 'Semua Kategori',
        allUnits: 'Semua Unit',
        allStatus: 'Semua Status',
        severity: 'Severity',
        workUnit: 'Unit',
        assignee: 'Assignee',
        status: 'Status',
        deadline: 'Deadline',
        ref: 'Ref',
        judul: 'Judul',
        open: 'Terbuka',
        inProgress: 'Dalam Penanganan',
        resolved: 'Selesai Ditindaklanjuti',
        closed: 'Ditutup & Terverifikasi',
        lateDays: (n: number) => `Terlambat ${n} hari`,
        leftDays: (n: number) => `Sisa ${n} hari`,
        deadlineToday: 'Deadline hari ini',
        verifiedOn: (d: string) => `Diverifikasi · ${d}`,
        done: 'Selesai',
        overdue: 'terlambat',
        noFindings: 'Belum ada temuan yang cocok dengan kriteria pencarian.',
        detailTitle: 'Detail Temuan',
        controlLabel: 'Kontrol',
        picLabel: 'PIC',
        unitLabel: 'Unit Kerja',
        notesLabel: 'Catatan Admin',
        close: 'Tutup',
    },
    temuan: {
        title: 'Temuan',
        subtitle: 'Temuan ketidaksesuaian lintas unit · SLA 14 hari',
        kanban: 'Kanban',
        list: 'List',
        searchPlaceholder: 'Cari temuan…',
        allSeverity: 'Semua Kategori',
        allUnits: 'Semua Unit',
        allStatus: 'Semua Status',
        severity: 'Severity',
        workUnit: 'Unit',
        assignee: 'Assignee',
        workUnitPic: 'Unit Kerja / PIC',
        status: 'Status',
        deadline: 'Deadline',
        ref: 'Ref',
        judul: 'Judul',
        open: 'Terbuka',
        inProgress: 'Dalam Penanganan',
        resolved: 'Selesai Ditindaklanjuti',
        closed: 'Ditutup & Terverifikasi',
        lateDays: (n: number) => `Terlambat ${n} hari`,
        leftDays: (n: number) => `Sisa ${n} hari`,
        deadlineToday: 'Deadline hari ini',
        verifiedOn: (d: string) => `Diverifikasi · ${d}`,
        done: 'Selesai',
        overdue: 'terlambat',
        noFindings: 'Belum ada temuan yang cocok dengan kriteria pencarian.',
        detailTitle: 'Detail Temuan',
        controlLabel: 'Kontrol',
        picLabel: 'PIC',
        unitLabel: 'Unit Kerja',
        notesLabel: 'Catatan Admin',
        close: 'Tutup',
    },
    risks: {
        title: 'Risk Register',
        subtitle: 'Daftar risiko keamanan informasi yang teridentifikasi beserta pemilik dan tingkat keparahan.',
        newRisk: 'Daftarkan Risiko Baru',
        comingSoon: 'Segera hadir',
        searchPlaceholder: 'Cari deskripsi risiko, nomor klausul, atau pemilik risiko…',
        allLevels: 'Semua Level Risiko',
        allStatus: 'Semua Status',
        allUnits: 'Semua Unit Kerja',
        totalRisks: 'Total Risiko',
        critical: 'Kritis (Critical)',
        high: 'Tinggi (High)',
        medium: 'Sedang (Medium)',
        low: 'Rendah (Low)',
        mitigated: 'Telah Dimitigasi',
        accepted: 'Risiko Diterima',
        open: 'Terbuka',
        code: 'Kode',
        risk: 'Risiko',
        controlClause: 'Klausul Kontrol & Risiko',
        levelLabel: 'Level Risiko',
        owner: 'Pemilik Risiko',
        statusMitigation: 'Status Mitigasi',
        actions: 'Aksi',
        noRisks: 'Belum ada risiko yang cocok dengan kriteria pencarian.',
        detailTitle: 'Detail Risiko',
        mitigationLabel: 'Rencana Tindakan Mitigasi',
        frameworkLabel: 'Framework',
        controlLabel: 'Kontrol SMKI Terkait',
        ownerLabel: 'Pemilik Risiko (Risk Owner)',
        noOwner: 'Belum ditugaskan',
        noMitigation: 'Belum ada rencana perlakuan risiko yang didokumentasikan.',
        registeredAt: 'Terdaftar pada',
        close: 'Tutup Panel',
        // Update modal
        updateTitle: 'Perbarui Status Risiko',
        updateDesc: 'Perbarui status mitigasi, level, pemilik, dan rencana tindakan.',
        updateStatus: 'Status Mitigasi',
        updateLevel: 'Level Risiko',
        updateOwner: 'Pemilik Risiko',
        updateMitigation: 'Rencana Mitigasi',
        updateMitigationPlaceholder: 'Jelaskan rencana tindakan mitigasi yang akan atau telah dilakukan…',
        updateOwnerPlaceholder: 'Nama pemilik atau unit penanggung jawab risiko',
        updateNotes: 'Catatan Admin',
        updateNotesPlaceholder: 'Catatan penolakan atau alasan perubahan status (wajib jika status diturunkan)…',
        updateNotesRequired: 'Catatan wajib diisi jika status diturunkan atau risiko ditolak.',
        updateSubmit: 'Simpan Perubahan',
        updateCancel: 'Batal',
        updateSuccess: 'Status risiko berhasil diperbarui.',
        updateError: 'Gagal memperbarui risiko. Silakan coba lagi.',
        levelRequired: 'Level risiko wajib dipilih.',
        statusRequired: 'Status wajib dipilih.',
    },
    audit: {
        title: 'Audit Trail',
        subtitle: 'Catatan perubahan data yang tidak dapat diubah (immutable).',
        totalLogs: 'Total Log',
        last24Hours: '24 Jam Terakhir',
        export: 'Export Log',
        cardTitle: 'Log Aktivitas',
        searchPlaceholder: 'Cari entitas atau ringkasan…',
        allActions: 'Semua Aksi',
        allEntities: 'Semua Entitas',
        allActors: 'Semua Aktor',
        dateFrom: 'Dari tanggal',
        dateTo: 'Sampai tanggal',
        colTime: 'Waktu',
        colActor: 'Aktor',
        colEntity: 'Entitas',
        colAction: 'Aksi',
        colSummary: 'Ringkasan',
        detail: 'Detail',
        detailTitle: 'Detail Log',
        detailDesc: 'Perbandingan sebelum & sesudah perubahan.',
        timeLabel: 'Waktu',
        actorLabel: 'Aktor',
        entityLabel: 'Entitas',
        actionLabel: 'Aksi',
        field: 'Field',
        before: 'Sebelum',
        after: 'Sesudah',
        immutable: 'Log ini bersifat permanen dan tidak dapat dimodifikasi atau dihapus.',
        noLogs: 'Belum ada log aktivitas.',
        close: 'Tutup',
        changesLabel: 'Perubahan Field',
        action: {
            create: 'CREATE',
            update: 'UPDATE',
            delete: 'DELETE',
            verify: 'VERIFY',
            bulk_verify: 'BULK_VERIFY',
            export: 'EXPORT',
            upload: 'UPLOAD',
        },
    },
    bulkVerify: {
        title: 'Verifikasi Penilaian',
        subtitle: 'Tinjau dan verifikasi kepatuhan kontrol checklist yang diajukan oleh PIC unit kerja.',
        landingTitle: 'Pilih Sesi Penilaian',
        landingSubtitle: 'Pilih sesi penilaian unit kerja yang akan diverifikasi.',
        searchPlaceholder: 'Cari kode, klausul, atau judul kontrol…',
        allStatus: 'Semua Status Kepatuhan',
        allUnits: 'Semua Unit Kerja',
        allVerified: 'Semua Verifikasi',
        unverified: 'Belum Diverifikasi',
        verified: 'Sudah Diverifikasi',
        code: 'Kode Klausul',
        control: 'Kontrol / Klausul',
        workUnit: 'Unit Kerja',
        pic: 'PIC',
        status: 'Status Kepatuhan',
        evidence: 'Dokumen Bukti',
        verifiedBy: 'Status Verifikasi',
        selectAll: 'Pilih Semua',
        selected: (n: number) => `${n} entri dipilih`,
        approve: 'Setujui (Patuh)',
        reject: 'Tolak (Tidak Patuh)',
        approveSelected: 'Setujui Terpilih',
        rejectSelected: 'Tolak Terpilih',
        noSelection: 'Pilih minimal satu entri untuk diverifikasi.',
        confirmApproveTitle: 'Setujui entri terpilih?',
        confirmApproveDesc: (n: number) => `Anda akan menandai ${n} entri checklist sebagai Patuh.`,
        confirmRejectTitle: 'Tolak entri terpilih?',
        confirmRejectDesc: (n: number) => `Anda akan menandai ${n} entri checklist sebagai Tidak Patuh.`,
        notesLabel: 'Catatan Admin Kepatuhan',
        notesPlaceholder: 'Tuliskan catatan verifikasi untuk PIC (opsional)…',
        noEntries: 'Tidak ada entri checklist yang cocok dengan kriteria pencarian.',
        openEvidence: 'Lihat Dokumen Evidence',
        none: '—',
        verifiedOn: (d: string) => `Diverifikasi · ${d}`,
    },
    status: {
        compliant: 'Patuh',
        partial: 'Sebagian Patuh',
        non_compliant: 'Tidak Patuh',
        na: 'Tidak Berlaku',
        pending_verification: 'Menunggu Verifikasi',
        verified: 'Terverifikasi',
        rejected: 'Ditolak',
        approved: 'Disetujui',
        pending: 'Menunggu',
        automatic: 'Otomatis',
        open: 'Terbuka',
        in_progress: 'Dalam Penanganan',
        resolved: 'Selesai Ditindaklanjuti',
        closed: 'Ditutup & Terverifikasi',
        mitigated: 'Mitigasi',
        accepted: 'Diterima',
        low: 'Rendah',
        medium: 'Sedang',
        high: 'Tinggi',
        critical: 'Kritis',
        major: 'Mayor',
        minor: 'Minor',
        observation: 'Observasi',
    },
    admin: {
        users: {
            title: 'Manajemen User',
            subtitle: 'Kelola pengguna, role, dan unit kerja.',
            addUser: 'Tambah User',
            name: 'Nama',
            nameLabel: 'Nama Lengkap',
            createTitle: 'Tambah User',
            editTitle: 'Edit User',
            deleteTitle: 'Hapus User',
            deleteConfirm: (name: string) => `Hapus user "${name}"? Tindakan ini tidak dapat dibatalkan.`,
        },
        roles: {
            title: 'Manajemen Role',
            subtitle: 'Kelola role dan hak akses (permissions).',
            addRole: 'Tambah Role',
            name: 'Nama',
            label: 'Label',
            grants: 'Hak Akses',
            createTitle: 'Tambah Role',
            editTitle: 'Edit Role',
            deleteTitle: 'Hapus Role',
            deleteConfirm: (label: string) => `Hapus role "${label}"?`,
            noRoles: 'Belum ada role.',
        },
    },
    notificationsPage: {
        title: 'Notifikasi',
        subtitle: 'Pemberitahuan dan pembaruan yang ditujukan untuk Anda.',
        unread: 'Belum Dibaca',
        all: 'Semua',
        markAllRead: 'Tandai Semua Dibaca',
        emptyTitle: 'Tidak ada notifikasi',
        emptyDesc: 'Anda belum memiliki notifikasi apapun. Pembaruan temuan dan penilaian kontrol akan muncul di sini.',
        readChip: 'Sudah dibaca',
        newChip: 'Baru',
        delete: 'Hapus',
        deleteConfirm: 'Hapus notifikasi ini?',
        timeLabel: 'Waktu',
        openAction: 'Buka',
        unreadCount: (n: number) => `${n} belum dibaca`,
        toastUnreadTitle: 'Notifikasi Belum Dibaca',
        toastUnreadMessage: (n: number) =>
            n === 1 ? 'Anda memiliki 1 notifikasi yang belum dibaca.' : `Anda memiliki ${n} notifikasi yang belum dibaca.`,
        toastNewTitle: 'Notifikasi Baru',
        viewAll: 'Lihat Semua',
    },
    errors: {
        notFound: 'Halaman tidak ditemukan',
        forbidden: 'Anda tidak memiliki akses',
        serverError: 'Terjadi kesalahan pada server',
    },
} as const;

export type Strings = typeof id;
export type StringKey = {
    [K in keyof Strings]: Strings[K] extends string ? K : never;
}[keyof Strings];
