<?php

/*
|--------------------------------------------------------------------------
| RBAC Permission Matrix
|--------------------------------------------------------------------------
|
| Runtime source of truth for the permission matrix documented in
| docs/role-permissions.md. Seeded into the DB by RolesAndPermissionsSeeder;
| grants afterwards live in the database and can diverge from this file.
|
*/

return [
    'permissions' => [
        'dashboard' => [
            'dashboard.read',
            'dashboard.recent-activities',
        ],
        'checklist' => [
            'checklist.view',
            'checklist.read',
            'checklist.create',
            'checklist.update',
            'checklist.verify',
            'checklist.bulk-verify',
            'checklist.delete',
            'checklist.restore',
            'checklist.generate-monthly',
        ],
        'checklist-session' => [
            'checklist-session.view',
            'checklist-session.read',
            'checklist-session.create',
            'checklist-session.update',
            'checklist-session.delete',
            'checklist-session.restore',
        ],
        'control' => [
            'control.view',
            'control.read',
            'control.create',
            'control.update',
            'control.delete',
            'control.export',
            'control.import',
        ],
        'framework' => [
            'framework.view',
            'framework.read',
            'framework.create',
            'framework.update',
            'framework.delete',
        ],
        'evidence' => [
            'evidence.read',
            'evidence.upload',
            'evidence.delete',
            'evidence.restore',
        ],
        'finding' => [
            'finding.view',
            'finding.read',
            'finding.create',
            'finding.update',
            'finding.update-status',
            'finding.delete',
        ],
        'risk' => [
            'risk.view',
            'risk.read',
            'risk.create',
            'risk.update',
            'risk.delete',
        ],
        'work-unit' => [
            'work-unit.view',
            'work-unit.read',
            'work-unit.create',
            'work-unit.update',
            'work-unit.delete',
        ],
        'audit-log' => [
            'audit-log.view',
            'audit-log.read',
        ],
        'report' => [
            'report.read',
            'report.export',
        ],
        'user' => [
            'user.profileview',
            'user.managementview',
            'user.read',
            'user.create',
            'user.update',
            'user.delete',
        ],
    ],

    'roles' => [
        'superadmin' => [
            // dashboard
            'dashboard.read',
            'dashboard.recent-activities',
            // checklist
            'checklist.view',
            'checklist.read',
            'checklist.create',
            'checklist.update',
            'checklist.verify',
            'checklist.bulk-verify',
            'checklist.delete',
            'checklist.restore',
            'checklist.generate-monthly',
            // checklist-session
            'checklist-session.view',
            'checklist-session.read',
            'checklist-session.create',
            'checklist-session.update',
            'checklist-session.delete',
            'checklist-session.restore',
            // control
            'control.view',
            'control.read',
            'control.create',
            'control.update',
            'control.delete',
            'control.export',
            'control.import',
            // framework
            'framework.view',
            'framework.read',
            'framework.create',
            'framework.update',
            'framework.delete',
            // evidence
            'evidence.read',
            'evidence.upload',
            'evidence.delete',
            'evidence.restore',
            // finding
            'finding.view',
            'finding.read',
            'finding.create',
            'finding.update',
            'finding.update-status',
            'finding.delete',
            // risk
            'risk.view',
            'risk.read',
            'risk.create',
            'risk.update',
            'risk.delete',
            // work-unit
            'work-unit.view',
            'work-unit.read',
            'work-unit.create',
            'work-unit.update',
            'work-unit.delete',
            // audit-log
            'audit-log.view',
            'audit-log.read',
            // report
            'report.read',
            'report.export',
            // user
            'user.profileview',
            'user.managementview',
            'user.read',
            'user.create',
            'user.update',
            'user.delete',
        ],
        'admin_kepatuhan' => [
            'dashboard.read',
            'dashboard.recent-activities',
            'checklist.view',
            'checklist.read',
            'checklist.create',
            'checklist.update',
            'checklist.verify',
            'checklist.bulk-verify',
            'checklist.delete',
            'checklist.restore',
            'checklist.generate-monthly',
            'checklist-session.view',
            'checklist-session.read',
            'checklist-session.create',
            'checklist-session.update',
            'checklist-session.delete',
            'checklist-session.restore',
            'control.view',
            'control.read',
            'control.create',
            'control.update',
            'control.delete',
            'control.export',
            'control.import',
            'framework.view',
            'framework.read',
            'framework.create',
            'framework.update',
            'framework.delete',
            'evidence.read',
            'evidence.upload',
            'evidence.delete',
            'evidence.restore',
            'finding.view',
            'finding.read',
            'finding.create',
            'finding.update',
            'finding.update-status',
            'finding.delete',
            'risk.view',
            'risk.read',
            'risk.create',
            'risk.update',
            'risk.delete',
            'work-unit.read',
            'audit-log.view',
            'audit-log.read',
            'report.read',
            'report.export',
            'user.profileview',
        ],
        'koordinator_smki' => [
            'dashboard.read',
            'dashboard.recent-activities',
            'checklist.view',
            'checklist.read',
            'checklist-session.view',
            'checklist-session.read',
            'control.read',
            'framework.read',
            'evidence.read',
            'finding.view',
            'finding.read',
            'risk.view',
            'risk.read',
            'work-unit.read',
            'audit-log.view',
            'audit-log.read',
            'report.read',
            'report.export',
            'user.profileview',
            'user.managementview',
            'user.read',
        ],
        'auditor' => [
            'dashboard.read',
            'dashboard.recent-activities',
            'checklist.view',
            'checklist.read',
            'checklist-session.view',
            'checklist-session.read',
            'control.read',
            'framework.read',
            'evidence.read',
            'finding.view',
            'finding.read',
            'risk.view',
            'risk.read',
            'work-unit.read',
            'audit-log.view',
            'audit-log.read',
            'report.read',
            'report.export',
            'user.profileview',
            'user.managementview',
            'user.read',
        ],
        'pic' => [
            'dashboard.read',
            'checklist.view',
            'checklist.read',
            'checklist.create',
            'checklist.update',
            'checklist.verify',
            'checklist.delete',
            'checklist.restore',
            'checklist.generate-monthly',
            'checklist-session.view',
            'checklist-session.read',
            'checklist-session.create',
            'checklist-session.update',
            'checklist-session.delete',
            'checklist-session.restore',
            'control.read',
            'framework.read',
            'evidence.read',
            'evidence.upload',
            'evidence.delete',
            'evidence.restore',
            'finding.view',
            'finding.read',
            'finding.create',
            'finding.update',
            'finding.update-status',
            'finding.delete',
            'risk.view',
            'risk.read',
            'risk.create',
            'risk.update',
            'risk.delete',
            'work-unit.read',
            'user.profileview',
        ],
    ],
];
